### ISSUE TITLE
Download link is broken!

### ISSUE THREAD

**Issue by shiv19** [Codigami/CFAlertDialog#10]
also I'm not able to include the dependency through the maven url provided.

**Comment by WrathChaos** [comment]
+1
Please fix the gradle link

**Comment by h4ppysmile** [comment]
+1 dose not sync in android studio

**Comment by rahul-s** [comment]
@shiv19 @WrathChaos @h4ppysmile We are currently in the process of migrating the library to a new account. This will be available shortly. We are extremely sorry for the inconvenience.

**Comment by shiv19** [comment]
Awesome! Thank you so much. Please do let me know when it is available.

**Comment by grout-r** [comment]
Hello
Is there any way to download the library locally ?

**Comment by rahul-s** [comment]
The library has been migrated to a new account, and is live.
Please note the change in download instructions in the `Readme` file.

repositories link changed to:
```java
maven { url "https://dl.bintray.com/crowdfire/cfalertdialog" }
```

and package link changed to:
```java 
compile 'com.crowdfire.cfalertdialog:cfalertdialog:1.0.1'
```

cc: @shiv19 @h4ppysmile @WrathChaos @grout-r 

PS: We are also in the process of uploading this to `JCenter` and `Maven` repositories.

**Comment by shiv19** [comment]
Thank you @rahul-s :)

**Comment by shiv19** [comment]
Thank you @rahul-s
I was able to build a nativescript plugin using CFAlert Dialog
https://www.npmjs.com/package/nativescript-cfalert-dialog

I'll support iOS also next :)

Big thanks to you!

**Comment by shiv19** [comment]
@rahul-s iOS support also added :)
