### ISSUE TITLE
Action buttons on same line

### ISSUE THREAD

**Issue by bartbergmans** [Codigami/CFAlertDialog#14]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/Codigami/CFAlertDialog/blob/develop/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/Codigami/CFAlertDialog/blob/develop/README.md)
* [x] I have searched for a similar issue in the [project](https://github.com/Codigami/CFAlertDialog/issues) and found none

### Issue Info

 Info                          | Value                               |
-------------------------------|-------------------------------------|
 Platform Name                 | Android
 Platform Version              | 7.0
 CFAlertDialog Version         | 1.2.0
 Integration Method            | gradle
 Xcode Version                 | 3.0
 Repro rate                    | 100%
 Repro with our demo prj       | Yes
 Demo project link             | n/a

### Issue Description and Steps

Buttons can't be placed next to each other. When I have two buttons and I align one to START and one to END they appear at the START and END position but below each other. When I give both buttons position END they are both at END but also below each other. Is it possible to put the buttons on the same line?

**Comment by rahul-s** [comment]
@bartbergmans Sorry, but this feature is not yet supported in this library. We may add this feature later on.
