### ISSUE TITLE
Prevent StatusBar from showing when using CFAlertDialog

### ISSUE THREAD

**Issue by uzman** [Codigami/CFAlertDialog#16]
My app is fullscreen activity. 
when I show the alert dialog it displays status bar. after alert dialog goes away status bar is gone.
how can I prevent showing status bar?

on create method:

requestWindowFeature(Window.FEATURE_NO_TITLE);
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);

Also I set the values in my style:

        <item name="windowNoTitle">true</item>
        <item name="windowActionBar">false</item>
        <item name="android:windowFullscreen">true</item>
        <item name="android:windowContentOverlay">@null</item>

**Comment by rahul-s** [comment]
@uzman Use this method to initiate the Alert:
`new CFAlertDialog.Builder(context, style);`
You can pass the style used above to the constructor.

**Comment by uzman** [comment]
thanks. 
you can close issue.
