### ISSUE TITLE
When can we expect support for AndroidX

### ISSUE THREAD

**Issue by rishabh876** [Codigami/CFAlertDialog#22]
As android has moved on to AndroidX. Old libraries that do not support AndroidX require an extra step during compilation - Jetifier.

> Jetifier tool migrates support-library-dependent libraries to rely on the equivalent AndroidX packages instead. The tool lets you migrate an individual library directly, instead of using the Android gradle plugin bundled with Android Studio.

Jetifier takes extra time during compilation. Making it slow.

Most of the libraries have already moved on to AndroidX. But I can't remove Jetifier until and unless all libraries in my project have support for AndroidX. 

When can we expect AndroidX support?

**Comment by rahul-s** [comment]
Hey @rishabh876 This is planned to be taken up soon. Will update here.
