### ISSUE TITLE
How to get ClickListener from costum header or footer with kotlin

### ISSUE THREAD

**Issue by majid1605** [Codigami/CFAlertDialog#23]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/Codigami/CFAlertDialog/blob/develop/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/Codigami/CFAlertDialog/blob/develop/README.md)
* [x] I have searched for a similar issue in the [project](https://github.com/Codigami/CFAlertDialog/issues) and found none

### Issue Info

 Info                          | Value                               |
-------------------------------|-------------------------------------|
 Platform Name                 | e.g. Android
 Platform Version              | e.g. 4.4
 CFAlertDialog Version         | e.g. 2.1.1
 Integration Method            | e.g. gradle / manually
 Xcode Version                 | e.g. Android Studio 3.2

**Comment by pocketutilities** [comment]
I would also like to know the answer to this. I wanted to get text from Edittext which is added in custom view using 
builder.setFooterView(R.layout.some_footer_layout);

**Comment by rahul-s** [comment]
@majid1605 @pocketutilities Both of these can be achieved as follows
1. Inflate the layout into a View object
```View customView = getLayoutInflater().inflate(R.layout.child, null);```
2. Set the `OnClickListener`, `TextWatcher` or any such listener to the appropriate view.
3. Add this view as `Header/Footer`.

Let me know if you need any further help. You may also refer to the demo project in this repo.

**Comment by majid1605** [comment]
Why does my first code work but the second code doesn't work?
```
customView.myBtnID.setOnClickListener {
                    Toast.makeText(this, "test", Toast.LENGTH_SHORT).show()
        }
```

```
customView.setOnClickListener {
        when(it.id)
{
R.id.myBtnID->
{
                    Toast.makeText(this, "test", Toast.LENGTH_SHORT).show()
}
}
```

and how dismiss dialog after click myBtn?or any object on my dialog?

**Comment by pocketutilities** [comment]
Awesome that worked for me

**Comment by rahul-s** [comment]
@majid1605 You may keep a reference to the dialog using:
`CFAlertDialog alertDialog = builder.show();`
And on click listeners of any view you can call dismiss on the `alertDialog`.
