### ISSUE TITLE
Getting rid of statusbar color override?

### ISSUE THREAD

**Issue by StevenRogre** [Codigami/CFAlertDialog#27]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/Codigami/CFAlertDialog/blob/develop/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/Codigami/CFAlertDialog/blob/develop/README.md)
* [x] I have searched for a similar issue in the [project](https://github.com/Codigami/CFAlertDialog/issues) and found none

### Issue Info

 Info                          | Value                               |
-------------------------------|-------------------------------------|
 Platform Name                 | Android
 Platform Version              | 9.0
 CFAlertDialog Version         | 1.1.0
 Integration Method            |  gradle
 IDE Version                 | Android Studio 3.3
 Repro rate                    | all the time (100%)
 Repro with our demo prj       | does it happen with our demo project? - YES
 Demo project link             | link to a demo project that highlights the issue

### Issue Description and Steps

Hi, great library. Could someone please tell me how do I get rid of the statusbar color getting override? Stock alertDialog doesn't touch or do anything to it which gives a seamless feel but this library makes it light gray which looks bad, especially since my app uses AMOLED dark UI.

Couldn't find the option so opening an issue. Thank you.

**Comment by StevenRogre** [comment]
Seems like switching CFDialog theme to "Theme.AppCompat.Dialog.Alert" fixed my issue.

**Comment by Testator** [comment]
how do I programmatically override the color of the status bar to transparent?

i did not load the library directly into my project. Thanks in advance.
