### ISSUE TITLE
Adjustable dialog's width

### ISSUE THREAD

**Issue by ionate12** [Codigami/CFAlertDialog#33]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/Codigami/CFAlertDialog/blob/develop/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/Codigami/CFAlertDialog/blob/develop/README.md)
* [x] I have searched for a similar issue in the [project](https://github.com/Codigami/CFAlertDialog/issues) and found none

### Issue Info

 Info                          | Value                               |
-------------------------------|-------------------------------------|
 Platform Name              Android   | e.g. Android
 Platform Version        8.0      | e.g. 8.0
 CFAlertDialog Version    1.3.0    | e.g. 2.1.1
 Integration Method      gradle      | e.g. gradle / manually
 Xcode Version          Android Studio 3.4       | e.g. Android Studio 2.3

### Issue Description and Steps

Hi,
Is there any ways for me to adjust the dialog's width? Because it looks small on the big tablet like Samsung Galaxy Tab A 10.5".
Thank you in advance!

![image](https://user-images.githubusercontent.com/27364092/62745545-bff2e600-ba8e-11e9-94de-5fa43813a2cf.png)

**Comment by rahul-s** [comment]
@ionate12 Try setting the `dialogOuterMargin` param to the required size and the width of the dialog should adjust. Let me know if that doesn't work.

**Comment by ionate12** [comment]
> @ionate12 Try setting the `dialogOuterMargin` param to the required size and the width of the dialog should adjust. Let me know if that doesn't work.

That works perfectly. Thank you!
