### ISSUE TITLE
How to add a CUSTOM VIEW as the main content?

### ISSUE THREAD

**Issue by mori-honest** [Codigami/CFAlertDialog#9]

**Comment by rahul-s** [comment]
@mori-honest Setting either the header/footer with the other properties null will give you the desired result. Use the `setHeaderView()` or `setFooterView()`
You may either pass an xml layout as the view or a custom view created programmatically.

Please revert if u have any further queries.

**Comment by rahul-s** [comment]
Here's a code snippet for reference:
```
// Create Alert using Builder
CFAlertDialog.Builder builder = new CFAlertDialog.Builder(this)
    .setDialogStyle(CFAlertDialog.CFAlertStyle.ALERT)
    .setHeaderView(<YOUR_CUSTOM_VIEW>);
        
// Show the alert
builder.show();
```
